### ISSUE TITLE
Add Button to Main page

### ISSUE THREAD

**Issue by DPLATA** [El-Dato-MX/eldatomx_main#2]
**Task:** Add a button to the main app screen that redirects to [stat head.eldatomx.com](https://stathead.eldatomx.com) with an appealing label and accompanying text nearby. Leave the styling and exact copy for the label open for creative input.

**Comment by DPLATA** [comment]
Once button is on prod we can start distributing main site [eldatomx.com](www.eldatomx.com).

**Comment by jangala-laxman** [comment]
Hi @DPLATA ,
 I would like to work on this issue. Can you assign it to me please..
